// Pure HTML views; adoption.js owns navigation, drafts and browser persistence.
(function (root) {
  const cfg = root.SIGNALDESK_RESEARCH_CONFIG, model = root.SIGNALDESK_RESEARCH_MODEL;
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  const link = (url, label) => model.safeUrl(url) ? `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>` : esc(label);
  const when = v => v && Number.isFinite(Date.parse(v)) ? (/^\d{4}-\d{2}-\d{2}$/.test(v) ? v : new Date(v).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })) : "Not provided";
  const number = (v, unit = "") => Number.isFinite(v) ? `${new Intl.NumberFormat("en", { notation: Math.abs(v) >= 1000000 ? "compact" : "standard", maximumFractionDigits: 2 }).format(v)}${unit ? ` ${esc(unit)}` : ""}` : "Not disclosed / unavailable";
  const viewButton = (view, label) => `<button class="tech-text-button" type="button" ${/source health|collection status/.test(label) ? "data-show-health" : `data-tech-view="${view}"`}>${label} →</button>`;
  const head = (title, description, action = "") => `<div class="tech-view-head"><div><h3>${title}</h3><p>${description}</p></div>${action}</div>`;
  const empty = (title, description) => `<div class="tech-empty"><h4>${title}</h4><p>${description}</p></div>`;
  function brief(themes, research, monitor, followed, status) {
    const b = model.buildBrief({ themes, research, monitor, followed });
    const recent = b.reviews.slice(0, 4), changes = b.documents.slice(0, 4);
    const checked = research ? `Snapshot assembled ${when(research.generatedAt)}` : status === "loading" ? "Loading saved research…" : "Saved research could not be loaded";
    return `<section class="intel-brief-lead"><div><p class="tech-sector">YOUR RESEARCH BRIEF</p><h3>What changed.<br>What needs proof.</h3><p>Follow the path from a promising technology to something people actually use—and the businesses behind it.</p></div><div class="intel-brief-status"><span class="tech-health health-${b.checkedState === "current" ? "current" : "stale"}">${esc(checked)}</span><p>${followed.length ? `${followed.length} followed technologies` : "All tracked technologies · follow a theme to personalize"}</p><p>${research?.coverage?.readableSources ?? "—"}/${cfg.sources.length} readable sources · ${Object.keys(research?.companies || {}).length}/${cfg.companies.length} company records</p>${viewButton("inbox", "Inspect source health")}</div></section>
      ${b.checkedState !== "current" || status === "error" ? `<p class="tech-inbox-warning">${status === "loading" ? "Loading the saved collection. Reviewed profiles remain available below." : "The latest research could not be confirmed. Any retained snapshot keeps its original date. Do not interpret a quiet brief as evidence that nothing changed."}</p>` : ""}
      <div class="intel-brief-grid"><section class="intel-brief-block"><div class="intel-block-head"><h4>New evidence to review</h4><span>${changes.length ? b.documents.length : "No new changes"}</span></div>
      ${changes.length ? changes.map(d => `<article class="intel-brief-item"><span class="tech-kind">${esc(d.headlineSignal)} · unreviewed</span><h5><button class="tech-text-button" data-review="${esc(d.id)}">${esc(d.title)}</button></h5><p class="tech-meta">${esc(d.owner)} · detected ${when(d.detectedAt)}</p></article>`).join("") : `<p class="intel-quiet">No new document changes in your scope in the last seven days. Initial source inventories are available in Review, without being presented as fresh news.</p>`}${viewButton("inbox", "Open review queue")}</section>
      <section class="intel-brief-block"><div class="intel-block-head"><h4>What could change the story</h4><span>Next proof</span></div>${b.checkpoints.slice(0, 3).map(c => `<article class="intel-brief-item"><button class="tech-text-button" data-open-tech="${c.id}">${esc(c.name)}</button><p>${esc(c.check)}</p><span class="tech-meta ${c.overdue ? "tech-warning" : ""}">${c.overdue ? "Editorial review overdue" : "Editorial review due"} ${esc(c.due)} · not a company event</span></article>`).join("")}</section></div>
      <div class="intel-focus-heading"><h4>Go deeper on your two focus areas</h4><p>Compare the evidence, not the ambition.</p></div><div class="intel-focus-grid"><button class="intel-focus-card" data-tracker="batteries"><span class="tech-sector">ENERGY · ${cfg.programs.length} REVIEWED PROGRAMS</span><strong>Solid-state batteries <span>↗</span></strong><span>Cell results → qualification → repeatable production</span></button><button class="intel-focus-card" data-tracker="satellite"><span class="tech-sector">CONNECTIVITY · ${cfg.rollouts.length} SERVICE RECORDS</span><strong>Satellite-to-phone <span>↗</span></strong><span>Country, carrier, handset and real capabilities</span></button></div>
      <details class="intel-disclosure"><summary>Risks &amp; research gaps${b.failures.length ? ` · ${b.failures.length} source checks need attention` : ""}</summary>${b.unknowns.map(u => `<p><strong>${esc(u.name)}</strong> — ${esc(u.unknown)}. ${esc(u.risk)}</p>`).join("")}${viewButton("inbox", "Review collection status")}</details>
      ${recent.length ? `<section class="intel-reviewed"><h4>Recently reviewed</h4>${recent.map(r => `<article><span class="tech-kind">${r.kind === "target" ? "Company target" : "Human-reviewed claim"}</span><p>${esc(r.claim)}</p><p class="tech-meta">Reviewed by ${esc(r.reviewer)} · ${when(r.reviewedAt)} · ${link(r.url, r.owner)}</p></article>`).join("")}</section>` : ""}`;
  }
  function observations(entityId, metric, research) { return model.activeReviews(research?.reviews || []).filter(r => r.entityId === entityId && r.metricKey === metric).sort((a, b) => b.reviewedAt.localeCompare(a.reviewedAt)); }
  function metricValue(entityId, metric, research) {
    const row = observations(entityId, metric.id, research)[0];
    if (!row) return `<span class="intel-unknown">Not established</span>`;
    return `<strong>${row.qualifier === "lower-bound" ? "≥ " : row.kind === "target" ? "Target: " : ""}${row.value === null ? esc(row.claim) : number(row.value, row.unit)}</strong><small>${esc(row.period)} · ${esc(row.qualifier)} · ${link(row.url, row.owner)}</small><small>${esc(row.definition)} · ${esc(row.caveat)}</small>`;
  }
  function trackers(type, research, state) {
    const controls = `<div class="intel-segment" aria-label="Tracker type"><button class="tech-button" data-tracker="batteries" aria-pressed="${type === "batteries"}">Battery programs</button><button class="tech-button" data-tracker="satellite" aria-pressed="${type === "satellite"}">Satellite rollout</button></div>`;
    if (type === "satellite") {
      const rows = cfg.rollouts.filter(r => (state.country === "all" || r.country === state.country) && (state.serviceStatus === "all" || r.status === state.serviceStatus));
      return head("Satellite-to-phone rollout", "A service listing is not universal internet access. Compare the limits for a particular country, carrier and device.") + controls +
        `<div class="intel-inline-filters"><label>Country<select id="rolloutCountry"><option value="all">All countries</option>${[...new Set(cfg.rollouts.map(r => r.country))].map(c => `<option ${state.country === c ? "selected" : ""}>${esc(c)}</option>`).join("")}</select></label><label>Evidence<select id="rolloutStatus"><option value="all">All service records</option><option value="available" ${state.serviceStatus === "available" ? "selected" : ""}>Listed as available</option><option value="watch" ${state.serviceStatus === "watch" ? "selected" : ""}>Still to verify</option></select></label></div>
        ${rows.length ? `<div class="intel-rollouts">${rows.map(r => `<article class="intel-rollout"><div class="intel-block-head"><span class="tech-sector">${esc(r.country)}</span><span class="tech-kind ${r.status === "watch" ? "kind-target" : ""}">${r.status === "available" ? "Listed as available" : "Research gap"}</span></div><h4>${esc(r.operator)}</h4><p class="intel-rollout-capability">${esc(r.capability)}</p><dl class="intel-specs">${[["Carrier", r.carrier], ["Phones & OS", r.devices], ["Messaging", r.messaging], ["Apps", r.apps], ["Voice", r.voice], ["General internet", r.broadband], ["Coverage limits", r.coverage], ["Pricing", r.pricing]].map(([k, v]) => `<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join("")}</dl><p class="tech-caveat">${esc(r.limitations)}</p><p class="tech-meta">Page checked ${r.checkedAt} · publication date not provided · ${link(r.url, "Carrier / operator source")}</p><details class="intel-disclosure"><summary>Measured usage &amp; performance</summary>${[{ id: "users", label: "Active paying users" }, { id: "throughput", label: "Delivered throughput" }, { id: "reliability", label: "Connection success" }, { id: "capacity", label: "Busy-hour capacity" }].map(m => `<div class="intel-metric-row"><span>${m.label}</span><div>${metricValue(`rollout:${r.id}`, m, research)}</div></div>`).join("")}</details></article>`).join("")}</div>` : empty("No service records match", "Change the country or evidence filter. Missing coverage is not proof that a service is unavailable.")}`;
    }
    const programs = cfg.programs.filter(p => state.batteryStage === "all" || p.stage === state.batteryStage);
    const chosen = programs.filter(p => !state.compare.length || state.compare.includes(p.id));
    return head("Solid-state battery programs", "Compare what each program has demonstrated. Blank metrics mean the reviewed sources do not establish a comparable result.") + controls +
      `<div class="intel-inline-filters"><label>Program evidence<select id="batteryStage"><option value="all">All reviewed programs</option>${cfg.programs.map(p => `<option value="${p.stage}" ${state.batteryStage === p.stage ? "selected" : ""}>${esc(p.stageLabel)}</option>`).join("")}</select></label><span class="tech-meta">Select programs to narrow the comparison.</span>${state.compare.length ? '<button class="tech-button" data-clear-comparison>Show all programs</button>' : ""}</div>
      <div class="intel-program-grid">${programs.map(p => `<article class="intel-program"><div class="intel-block-head"><span class="tech-sector">${esc(p.ticker)}</span><label class="intel-compare"><input type="checkbox" data-compare="${p.id}" ${state.compare.includes(p.id) ? "checked" : ""}> Compare ${esc(p.company)}</label></div><h4>${esc(p.program)}</h4><p class="tech-kind">${esc(p.stageLabel)} · ${esc(p.chemistry)}</p><p>${esc(p.observed)}</p><p class="tech-meta">${esc(p.scope)}</p>${p.target ? `<p class="tech-warning">${esc(p.target.label)}</p>` : ""}<p class="intel-next"><strong>Next proof</strong>${esc(p.nextGate)}</p><p class="tech-meta">Published ${p.publishedAt} · checked ${p.checkedAt}<br>${link(p.url, p.owner)}</p><button class="tech-text-button" data-open-company="${p.ticker}">Company economics →</button></article>`).join("")}</div>
      ${chosen.length ? `<section class="intel-comparison"><h4>Comparable operating evidence</h4><p class="tech-meta">Targets retain their label. Cell and pack metrics are never combined. Inspect conditions before comparing numbers.</p><div class="intel-table-scroll" tabindex="0" role="region" aria-label="Battery metric comparison"><table class="intel-table"><thead><tr><th scope="col">Metric / definition</th>${chosen.map(p => `<th scope="col">${esc(p.company)}</th>`).join("")}</tr></thead><tbody>${cfg.batteryMetrics.map(m => `<tr><th scope="row">${esc(m.label)}<small>${esc(m.definition)}</small></th>${chosen.map(p => `<td>${metricValue(`program:${p.id}`, m, research)}</td>`).join("")}</tr>`).join("")}</tbody></table></div></section>` : empty("Select a visible program", "Your selected programs are outside this stage filter. Show all programs or change the stage.")}`;
  }
  function quote(row) {
    if (!row?.quote) return `<span class="intel-unknown">Quote unavailable</span>`;
    const q = row.quote, state = model.freshness(q.asOf, Date.now(), 96);
    return `<strong class="intel-price">${number(q.price, q.currency)}</strong><span class="tech-meta ${state !== "current" ? "tech-warning" : ""}">${state !== "current" ? "Stale / invalid quote" : "Saved quote · not a live trading feed"} · ${when(q.asOf)}</span>`;
  }
  function companies(themes, research, ticker) {
    const ids = new Set(themes.map(t => t.id)), all = cfg.companies.filter(c => c.themes.some(t => ids.has(t)));
    if (!ticker) return head("Company research", "Permanent coverage of the companies behind your themes. Their place here does not depend on today's stock-attention ranking.") + `<p class="tech-meta">${esc(research?.providerMode || "Research snapshot not loaded")}. Prices and financial reports have separate timestamps.</p><div class="tech-company-grid">${all.map(c => { const row = research?.companies?.[c.ticker]; return `<article class="tech-company"><div class="tech-company-top"><div><span class="tech-sector">${esc(c.role)}</span><h3><button class="tech-text-button" data-open-company="${c.ticker}">${esc(c.name)} ↗</button></h3></div><span class="tech-ticker">${c.ticker}</span></div><div class="intel-company-quote">${quote(row)}</div><p>${esc(c.economics)}</p><p class="tech-unknown">Technology-specific revenue share: not established.</p><p class="tech-meta">${c.risks.map(esc).join(" · ")}</p></article>`; }).join("")}</div>`;
    const c = cfg.companies.find(c => c.ticker === ticker); if (!c) return empty("Company not tracked", "Choose a company from the permanent universe.");
    const row = research?.companies?.[ticker], f = row?.financials || {}, context = model.financialContext(row);
    const labels = { cash: "Cash & equivalents", revenue: "Reported revenue", operatingCashFlow: "Operating cash flow", capex: "Capital expenditure", netIncome: "Net income / loss", shares: "Reported shares outstanding", debtCurrent: "Current long-term debt", debtNoncurrent: "Noncurrent long-term debt" };
    return `<button class="tech-text-button tech-back" data-company-back>← All companies</button><div class="tech-dossier-head"><div><p class="tech-sector">${esc(c.role)}</p><h3 id="companyProfileTitle" tabindex="-1">${esc(c.name)} <span class="tech-ticker">${c.ticker}</span></h3></div><div class="intel-company-quote">${quote(row)}</div></div><p class="tech-lead">${esc(c.economics)}</p>
      ${row?.quoteError || row?.factsError ? `<p class="tech-inbox-warning">${esc([row.quoteError, row.factsError].filter(Boolean).join(" · "))}. Last successful observations are retained with their original dates.</p>` : ""}
      <div class="intel-economics"><section><h4>Financial evidence</h4><p class="tech-meta">Company-level facts, not technology-specific revenue. Periods and accounting tags may differ; these rows are not a standardized peer valuation.</p><div class="intel-financial-grid">${Object.entries(labels).map(([key, label]) => { const fact = f[key]; return `<article><span>${label}</span><strong>${number(fact?.value, fact?.unit)}</strong>${fact ? `<small>${fact.start ? `${fact.start} → ` : "As of "}${fact.end}<br>${fact.form} · filed ${fact.filed} · ${link(fact.url, "SEC filing")}</small>${fact.stale ? '<small class="tech-warning">Historical only · reporting period over 450 days old</small>' : ""}` : '<small>No supported reported fact available</small>'}</article>`; }).join("")}</div></section>
      <aside class="intel-economic-notes"><h4>What reaches shareholders?</h4><p>Technology revenue, customer concentration, backlog conversion and product margins need separate disclosure. Group revenue is not a proxy.</p><h4>Valuation context</h4><p>${row?.valuation ? `Provider-reported market capitalization: ${number(row.valuation.marketCap, row.valuation.currency)} · ${when(row.valuation.asOf)}.` : "Market capitalization and valuation multiples are not available from the configured quote response. Price alone cannot establish whether a stock is cheap."}</p>${c.currencyCaution ? `<p class="tech-warning">${esc(c.currencyCaution)}</p>` : ""}<h4>Cash-only burn coverage</h4><p>${context.runwayMonths !== null ? `Cash and equivalents cover ${number(context.runwayMonths)} months of the historical operating burn. Other liquidity is excluded; this is not total runway.` : "Not calculated: compatible recent cash and negative operating-cash-flow observations are required."}</p><p class="tech-meta">${context.runwayCaveat}</p><h4>Risks to investigate</h4><ul>${c.risks.map(r => `<li>${esc(r)}</li>`).join("")}</ul></aside></div>
      <details class="intel-disclosure"><summary>Reported history &amp; dilution research</summary><p class="tech-meta">Share counts are unadjusted reported observations. Changes can reflect splits, multiple classes or issuance; they are not automatically labeled dilution.</p>${["shares", "revenue", "operatingCashFlow"].map(key => `<h4>${labels[key]}</h4><div class="intel-table-scroll"><table class="intel-table"><thead><tr><th>Period</th><th>Reported value</th><th>Filing</th></tr></thead><tbody>${(row?.histories?.[key] || []).slice(0, 6).map(p => `<tr><td>${p.start || "As of"} → ${p.end}</td><td>${number(p.value, p.unit)}</td><td>${link(p.url, `${p.form} · ${p.filed}`)}</td></tr>`).join("") || '<tr><td colspan="3">No reported history available</td></tr>'}</tbody></table></div>`).join("")}</details>
      <p class="tech-meta">Financial source checked ${when(row?.factsCheckedAt)} · quote source checked ${when(row?.quoteCheckedAt)}${row?.quote ? ` · ${link(row.quote.url, row.quote.provider)}` : ""}</p>${row?.latestFiling ? `<p>${link(row.latestFiling.url, row.latestFiling.title)}</p>` : ""}<button class="tech-button" data-stock="${c.ticker}">Look for current market attention</button>`;
  }
  function discovery(research, query, followed, savedOnly = false) {
    const data = research?.discovery;
    const rows = (savedOnly ? data?.archive || data?.candidates || [] : data?.candidates || []).filter(c => (!savedOnly || followed.includes(c.id)) && c.phrase.includes(query.toLowerCase().trim()));
    return head("Beyond the watchlist", "New phrases extracted from research and company headlines—not a hand-picked list of the next winners.", `<button class="tech-button" data-saved-discovery aria-pressed="${savedOnly}">${savedOnly ? "Show all leads" : `Saved leads · ${followed.length}`}</button>`) + `<p class="tech-inbox-warning">${esc(data?.note || "Discovery needs a successful research collection.")} Repeated coverage is a reason to investigate, not proof of adoption.</p><div class="intel-discovery-grid">${rows.map(c => `<article class="intel-discovery"><div class="intel-block-head"><span class="tech-kind">${esc(c.status)}</span><button class="tech-button" data-follow-discovery="${c.id}" aria-pressed="${followed.includes(c.id)}">${followed.includes(c.id) ? "Saved" : "Save lead"}</button></div><h4>${esc(c.phrase)}</h4><p>${c.recentDocuments} distinct ${c.recentDocuments === 1 ? "story" : "stories"} · ${c.owners.length} reporting owner${c.owners.length === 1 ? "" : "s"} · 14-day window ending ${esc(c.lastSeenAt || data.generatedAt.slice(0, 10))}</p><p class="tech-meta">${c.momentumPercent === null ? "Momentum not established · collecting comparable history" : `${number(c.momentumPercent)}% story-count change vs prior 14 days · sampled feeds only`}</p><p class="tech-meta">${c.evidenceTypes.map(esc).join(" · ")} — headline language, not verified events</p><details class="intel-disclosure"><summary>Inspect the source evidence</summary>${c.documentIds.map(id => research.documents.find(d => d.id === id)).filter(Boolean).map(d => `<p>${link(d.url, d.title)}<br><small>${esc(d.owner)} · published ${`${d.publishedAt.slice(0, 10)}${d.publishedAt.length > 10 ? " UTC" : ""}`}</small></p>`).join("")}</details></article>`).join("")}</div>${!rows.length ? empty("No discovery leads match yet", "The scanner needs relevant dated source documents. It will not invent a trend to fill this view. Clear the search or inspect source health. Saved leads are retained in the shared discovery archive for up to 90 days / 200 topics.") : ""}`;
  }
  function reviewQueue(themes, research, state) {
    const ids = new Set(themes.map(t => t.id)), reviewed = new Map((research?.reviews || []).map(r => [r.candidateId, r]));
    const query = (state.query || "").trim().toLowerCase();
    const discoveryIds = new Set((research?.discovery?.candidates || []).flatMap(c => c.documentIds));
    const rows = (research?.documents || []).filter(d => (state.reviewFilter === "all" || d.themes.length || discoveryIds.has(d.id) || reviewed.has(d.id)) && (!d.themes.length || d.themes.some(id => ids.has(id))) && (!query || [d.title, d.excerpt, d.owner, ...themes.filter(t => d.themes.includes(t.id)).map(t => t.name)].join(" ").toLowerCase().includes(query)) && (state.showDismissed || !state.dismissed.includes(d.id)) && (state.reviewFilter === "all" || (state.reviewFilter === "reviewed" ? reviewed.has(d.id) : !reviewed.has(d.id)))).sort((a, b) => Number(a.changeType === "baseline") - Number(b.changeType === "baseline") || (b.publishedAt || "").localeCompare(a.publishedAt || "") || b.detectedAt.localeCompare(a.detectedAt));
    return head("Evidence review", "Inspect the original, write a bounded claim, preserve its caveats. Saved drafts stay on this browser until exported and published through repository review.", `<button class="tech-button" data-export-reviews ${state.drafts.length ? "" : "disabled"}>Export ${state.drafts.length} review draft${state.drafts.length === 1 ? "" : "s"}</button>`) + `<div class="intel-inline-filters"><label>Queue<select id="reviewFilter"><option value="pending" ${state.reviewFilter === "pending" ? "selected" : ""}>Not yet reviewed</option><option value="reviewed" ${state.reviewFilter === "reviewed" ? "selected" : ""}>Published reviews</option><option value="all" ${state.reviewFilter === "all" ? "selected" : ""}>All document versions</option></select></label><span class="tech-meta">${rows.length} documents · first collections are labeled “Initial inventory”</span></div><div class="tech-inbox-list">${rows.slice(0, state.queueLimit).map(d => { const draft = state.drafts.find(r => r.candidateId === d.id), decision = reviewed.get(d.id); return `<article class="tech-inbox-item"><div><span class="tech-kind">${d.changeType === "baseline" ? "Initial inventory" : d.changeType === "revision" ? "Source revision" : "Newly detected document"} · ${decision ? `reviewed: ${esc(decision.decision)}` : draft ? "local draft · not published" : "unreviewed"}</span><h4>${link(d.url, d.title)}</h4><p class="tech-meta">${esc(d.owner)} · ${esc(d.tier)} · ${d.publishedAt ? `published ${`${d.publishedAt.slice(0, 10)}${d.publishedAt.length > 10 ? " UTC" : ""}`}` : "Publication date not extracted"} · detected ${when(d.detectedAt)}</p>${d.excerpt ? `<p class="intel-source-excerpt">${esc(d.excerpt)}</p>` : ""}${d.previousId ? `<details><summary>What changed in the saved excerpt</summary><p class="tech-meta">Before: ${esc(d.previousExcerpt || d.previousTitle || "No excerpt saved")}</p><p class="tech-meta">After: ${esc(d.excerpt || d.title)}. A page fingerprint can change beyond this excerpt; inspect the original before drawing conclusions.</p></details>` : ""}${decision ? `<p class="tech-meta">${esc(decision.reviewer)} · ${when(decision.reviewedAt)} · ${esc(decision.reason)}</p>` : ""}</div><div class="intel-queue-actions"><button class="tech-button" data-review="${d.id}">${decision ? "New review / correction" : draft ? "Edit local draft" : "Review evidence"}</button><button class="tech-text-button" data-dismiss="${d.id}">${state.dismissed.includes(d.id) ? "Restore" : "Dismiss locally"}</button></div></article>`; }).join("") || empty("No documents in this queue", "Change the review filter or inspect source health. Missing documents do not mean there were no developments.")}</div>${rows.length > state.queueLimit ? '<button class="tech-button" data-more-reviews>Show 24 more documents</button>' : ""}`;
  }
  function reviewEditor(document, themes, reviews, draft = {}) {
    const d = document, value = (key, fallback = "") => esc(draft[key] ?? fallback);
    const option = (v, label, key, fallback) => `<option value="${v}" ${(draft[key] || fallback) === v ? "selected" : ""}>${label}</option>`;
    return `<button class="tech-text-button tech-back" data-cancel-review>← Review queue</button>${head("Review a source claim", "Your draft is private to this browser. Saving it does not verify or publish a claim.", draft.id ? `<button type="button" class="tech-text-button" data-discard-review="${esc(d.id)}">Discard local draft</button>` : "")}<p>${link(d.url, d.title)}</p><p class="tech-meta">${esc(d.owner)} · ${d.publishedAt ? `published ${`${d.publishedAt.slice(0, 10)}${d.publishedAt.length > 10 ? " UTC" : ""}`}` : "Publication date unknown"}</p>${d.excerpt ? `<blockquote class="intel-source-excerpt">${esc(d.excerpt)}</blockquote>` : ""}
      <form id="evidenceReviewForm" class="intel-review-form"><div id="reviewErrors" role="alert" class="tech-warning"></div><div class="intel-form-grid"><label>Reviewer name<input name="reviewer" required maxlength="100" value="${value("reviewer")}"></label><label>Decision<select name="decision">${option("accepted", "Accept a bounded claim", "decision", "accepted")}${option("rejected", "Reject / not useful evidence", "decision")}</select></label><label>Technology<select name="themeId">${themes.map(t => option(t.id, esc(t.name), "themeId", d.themes[0] || themes[0].id)).join("")}</select></label><label>Evidence kind<select name="kind">${[["research", "Research result"], ["pilot", "Pilot / test"], ["rollout", "Available capability"], ["adoption", "Reported adoption"], ["target", "Company target"]].map(([v, l]) => option(v, l, "kind", "research")).join("")}</select></label></div>
      <label>What does the source actually establish?<textarea name="claim" rows="3" maxlength="2000">${value("claim")}</textarea></label><label>Why accept or reject it?<textarea name="reason" rows="2" required minlength="10" maxlength="2000">${value("reason")}</textarea></label><div class="intel-form-grid"><label>Metric / claim label<input name="metric" value="${value("metric")}" maxlength="160"></label><label>Reporting period / scope<input name="period" value="${value("period")}" maxlength="160"></label><label>Publication date (leave blank if unknown)<input type="date" name="publishedAt" value="${value("publishedAt", d.publishedAt?.slice(0, 10) || "")}"></label><label>Qualifier<select name="qualifier">${[["reported", "Reported, not exact"], ["exact", "Exact reported number"], ["lower-bound", "Lower bound (at least / over)"], ["target", "Target, not achieved"], ["observed-page", "Observed on an undated page"]].map(([v, l]) => option(v, l, "qualifier", "reported")).join("")}</select></label><label>Numeric value (optional)<input name="value" type="number" step="any" value="${value("value")}"></label><label>Unit (use “statement” for qualitative claims)<input name="unit" value="${value("unit", "statement")}" maxlength="80"></label></div><label>Definition / conditions / geography<textarea name="definition" rows="2" maxlength="1000">${value("definition")}</textarea></label><label>Limitations and alternative explanations<textarea name="caveat" rows="2" maxlength="1000">${value("caveat")}</textarea></label>
      <details class="intel-disclosure" ${draft.entityId || draft.supersedes ? "open" : ""}><summary>Attach to a tracker or correct earlier evidence</summary><div class="intel-form-grid"><label>Tracker record<select name="entityId"><option value="">No tracker attachment</option>${[...cfg.programs.map(p => [`program:${p.id}`, p.program]), ...cfg.rollouts.map(r => [`rollout:${r.id}`, `${r.operator} · ${r.country}`])].map(([v, l]) => option(v, esc(l), "entityId")).join("")}</select></label><label>Tracker metric<select name="metricKey"><option value="">No tracker metric</option>${[...cfg.batteryMetrics.map(m => [m.id, m.label]), ["users", "Active paying users"], ["throughput", "Delivered throughput"], ["reliability", "Connection success"], ["capacity", "Busy-hour capacity"]].map(([v, l]) => option(v, l, "metricKey")).join("")}</select></label><label>Supersedes evidence ID<select name="supersedes"><option value="">New evidence (no correction)</option>${[...themes.flatMap(t => t.evidence.map(e => [e.id, `${t.name}: ${e.metric}`])), ...model.activeReviews(reviews).map(r => [r.id, r.claim])].map(([v, l]) => option(v, esc(l), "supersedes")).join("")}</select></label></div></details><div class="intel-form-actions"><button class="tech-button" type="submit">Save local review draft</button><button class="tech-text-button" type="button" data-cancel-review>Back without saving</button></div></form>`;
  }
  root.SIGNALDESK_RESEARCH_VIEWS = { brief, trackers, companies, discovery, reviewQueue, reviewEditor };
})(window);
